apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: jojomak/auth
          env:
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: final_project
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TOKEN_EXPIRE_PERIOD
              value: '15m'
            - name: REFRESH_TOKEN_EXPIRE_PERIOD
              value: '7d'
            - name: DB_URI
              value: 'mongodb://auth-mongo-service:27017/auth'
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-key
                  key: APP_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
